name: Update Subscriptions

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 自动执行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pyyaml

    - name: Run update script
      run: python update.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add sub/*.txt
        git commit -m "Auto update subscriptions" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/dapei0402/jiedian.git HEAD:main
